### ISSUE TITLE
Jest Testing: Cannot read property 'style' of undefined

### ISSUE THREAD

**Issue by bitshadow** [l-urence/react-native-autocomplete-input#78]
Fails white testing with jest.
"react": "16.2.0",
"react-native": "0.53.0",
"jest": "22.3.0"

```
 FAIL  src/components/AutoComplete/AutoCompleteComponent.test.js
  ● Test suite failed to run

    TypeError: Cannot read property 'style' of undefined

      1 | // @flow
    > 2 | import Autocomplete from 'react-native-autocomplete-input';
      3 | import React, { Component } from 'react';
      4 | import {
      5 |   Platform,

      at Object.<anonymous> (node_modules/react-native-autocomplete-input/index.js:186:450)
      at Object.<anonymous> (src/components/AutoComplete/AutoCompleteComponent.js:2:35)
      at Object.<anonymous> (src/components/AutoComplete/AutoCompleteComponent.test.js:5:28)
```

**Comment by l-urence** [comment]
Did you try the setup for jest described in the readme?

**Comment by bitshadow** [comment]
My bad sorry for the trouble..
